name: hitchhiker
description: Entrance to oyasumi.space
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/

  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/OMORI_GAME2.ttf
    - family: GameFontJP
      fonts:
        - asset: assets/fonts/HuiFontP29.ttf
